# -*- coding: utf-8 -*-
"""movie_recomendation_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V-xxJUyjeHVhHkOS4oLrAWDYXywRnuZz
"""

# Import required libraries
import pandas as pd
import numpy as np
from ast import literal_eval
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from nltk.stem.porter import PorterStemmer
import requests
import gradio as gr

# Load and preprocess data
movies=pd.read_csv("tmdb_5000_movies.csv")
credits=pd.read_csv("tmdb_5000_credits.csv")

movies.head()

movies.shape

credits.head()

# Merge the two datasets on movies
movies=movies.merge(credits,on="title")
movies.head()

movies.shape

movies["production_companies"].values

#genres
#id
#keywords
#title
#overview
#cast
#crew


#Keep only required columns
movies=movies[["movie_id","title","overview","genres","keywords","cast","crew"]]
movies

movies.isnull().sum()

movies.dropna(inplace=True)

movies.duplicated().sum()

movies['genres'].iloc[0]

#ast.literal_eval(obj)
#Converts a string like this:
#"[{\"id\": 28, \"name\": \"Action\"}, {\"id\": 12, \"name\": \"Adventure\"}]" into a real Python object:
#[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}]

from ast import literal_eval   # to convert strings of lists/dictionaries into actual Python objects.
def convert(obj):
  l=[]
  for i in literal_eval(obj):
    l.append(i["name"])
  return l

movies['genres']=movies['genres'].apply(convert)

movies.head()

movies['keywords'].iloc[0]

movies['keywords']=movies['keywords'].apply(convert)

movies.head()

movies['cast'][1]

def convert3(obj):
  l=[]
  count=0
  for i in literal_eval(obj):
    if count !=3:
      l.append(i["name"])
      count=+1
    else:
      break
  return l

movies['cast']=movies['cast'].apply(convert3)

movies.head()

movies['crew'][0]

def fetch (obj):
  l=[]
  for i in literal_eval(obj):
    if i['job']=="Director":
      l.append(i["name"])
  return l

movies["crew"]=movies["crew"].apply(fetch)

movies.head()

movies['overview']=movies['overview'].apply(lambda x:x.split())

movies.head()

# removing the spaces in each word
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

movies.head()

# Combine all text columns into one: 'tags'
movies['tags']= movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

movies.head()

# new dataframe after combining all text columns into one: 'tags'
new_df=movies[['movie_id','title','tags']]
new_df

new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

new_df.head()

new_df['tags'][0]

# Convert to lowercase and apply stemming
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

new_df.head()

#stemming is done with PosterStemmer/(Text Processing)
import nltk
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

def stem(text):
  a = []
  for i in text.split():
    a.append(ps.stem(i))
  return " ".join(a)

# Apply stemming to the 'tags' column
new_df['tags']=new_df['tags'].apply(stem)

# Vectorize the tags column
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words="english")   #Create the Vectorizer
vectors=cv.fit_transform(new_df['tags']).toarray()           #Convert text into vectors
vectors

#To featch a list of the feature names
feature_names=cv.get_feature_names_out()  #get_feature_names_out function returns a list of the feature names
for word in feature_names:
  print(word)

#Measure similarity between movies based on text(vectors).
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vectors)
similarity[0]

"""**Build a recommender function using this similarity matrix.**"""

# returns 5 recommended movies and movie_id function

def recommended(movie):
  # Finds the index of the selected movie in the dataset
  movie_index=new_df[new_df['title'].str.lower() == movie.lower()].index[0]

  # Retrieves similarity scores for the selected movie
  distance=similarity[movie_index]

  # Gets top 5 similar movies (excluding the movie itself)
  movie_list=sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[1:6]

  recommendations=[]
  for i in movie_list:
    movie_id= new_df.iloc[i[0]].movie_id
    title= new_df.iloc[i[0]].title
    recommendations.append((title,movie_id))
  return recommendations

recommended("Avatar")

"""**Show posters using TMDB API.**"""

#fetch_poster() Function
import requests

import os
API_KEY = os.getenv("TMDB_API_KEY") # TMDB API key

def fetch_poster(movie_id):
    # Construct the URL to fetch movie details using TMDB API
    url = f'https://api.themoviedb.org/3/movie/{movie_id}?api_key={API_KEY}&language=en-US'

    # Send a GET request to the API and convert the response to JSON
    data = requests.get(url).json()

    # Extract the poster path from the response
    poster_path = data.get('poster_path')

    # If a poster path exists, create the full URL and return it
    if poster_path:
        full_path = "https://image.tmdb.org/t/p/w500" + poster_path
        return full_path
    else:
    # If no poster is available, return None
        return None

"""**Created a Web Gradio app with a dropdown and textbox**"""

# Gradio interface function
def recommend_movies(movie_name):
    try:
        # Call the recommended() function to get recommended movies
        # It should return a list of (title, movie_id) tuples
        recommendations = recommended(movie_name)

        # Lists to store poster URLs and movie titles
        movie_posters = []
        movie_titles = []

        # Loop through each recommended movie
        for title, movie_id in recommendations:
            movie_titles.append(title)    # Add the title to the list
            movie_posters.append(fetch_poster(movie_id))   # Fetch and add the poster URL

        # Combine poster URLs and titles into a list of tuples and return
        return [(poster, title) for poster, title in zip(movie_posters, movie_titles)]

    except:
        # If an error occurs (e.g., movie not found), return a placeholder image with a message
        return [("https://via.placeholder.com/150", "Movie not found. Try another.")]

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install gradio

# Gradio interface
import gradio as gr

# Extract all movie titles from the dataset to create dropdown options
movie_list = new_df['title'].values.tolist()

# Create Gradio app
interface = gr.Interface(
    fn=recommend_movies,       # Function to be called when the user selects a movie
    inputs=gr.Dropdown(choices=movie_list, label="Select a Movie"),         # Dropdown input with movie titles
    outputs=gr.Gallery(label="Recommended Movies"),        # Output displayed as a gallery of posters with titles
    title="Movie Recommendation System with Posters",       # Title shown at the top of the app
    description="Select a movie to get top 5 similar movie recommendations with posters."      # Short description
)

# Launch the Gradio interface in the web browser
interface.launch()